<?php
return array('allnames'=>array(
    'female'=>array(
        'emma',
        'taylor',
        'sophia',
        'isabella',
        'ava',
        'robin',
        'emily',
        'angel',
        'madison',
        'charlotte',
    ),
    'male'=>array(
        'noah',
        'liam',
        'mason',
        'jacob',
        'william',
        'ethan',
        'michael',
        'alexander',
        'james',
        'daniel',

    )
),
    'furnitures'=>array(
	    'bigobject'=>array(
    		'sofa'=>array('loc_id'=>'112','pose'=>'(-5.864,1.767,3.131)'),
    		'dining_table'=>array('loc_id'=>'113','pose'=>'(3.790,-1.085,0.027)'),
    		'tv_stand'=>array('loc_id'=>'114','pose'=>'(-5.393,4.124,1.442)'),
    		'mcs_table'=>array('loc_id'=>'115','pose'=>'(-1.968,1.958,1.536)'),
    		'computer_desk'=>array('loc_id'=>'116','pose'=>'(-2.727,0.934,-3.138)'),
    		'bed'=>array('loc_id'=>'117','pose'=>'(2.332,2.762,1.600)'),
    		'cupboard'=>array('loc_id'=>'118','pose'=>'(5.163,-2.267,-1.563)'),
    		'kitchen_table'=>array('loc_id'=>'119','pose'=>'(7.482,3.646,0.022)'),
    		'cooking_table'=>array('loc_id'=>'120','pose'=>'(6.335,3.613,-3.129)'),
    		'bookshelf'=>array('loc_id'=>'121','pose'=>'(7.636,0.117,0.096)'),
            'fridge'=>array('loc_id'=>'122','pose'=>'(7.381,1.673,-0.031)'),
            'desk'=>array('loc_id'=>'123','pose'=>'(2.986,2.324,0.023)'),
            'living_shelf'=>array('loc_id'=>'124','pose'=>'(-6.141,-2.418,-3.027)'),
    	    'fixed_me'=>array('loc_id'=>'125','pose'=>'(2.890,-1.426,1.558)'),
	    ),
	    'smallobject'=>array(
            "herb_tea","mocha_coffe","asam",
            "fries","chewing_gum",
            "cup_noodle","cake","apple",
            "potato_chips","peach_jelly","sandwich_biscuit",
            "bowl","plate","storage_box",
            "collar_cleaner",
        ),
        'human'=>array(
            'person',
            'me',
            'agent',
        )
    ),
    'doors'=>array(
	    'entry'=>array('loc_id'=>'200','point'=>'(0,0,0)','id'=>'door_a','ref'=>''),
	    'exit'=>array('loc_id'=>'201','point'=>'(9.621,-2.358,0.025)','id'=>'door_b','ref'=>''),
	),
    'rooms'=>array(
	    'apartment'=>array('loc_id'=>'102','point'=>'(9.621,-2.358,0.025)','id'=>'apartment'),
		'workspace'=>array('loc_id'=>'103','point'=>'(-0.312,-0.057,2.348)','id'=>'workspace'),
		'living_room'=>array('loc_id'=>'104','point'=>'(-5.22,-2.24,2.35619)','id'=>'living_room'),
		'dining_room'=>array('loc_id'=>'105','point'=>'(2.522,-1.406,0.603)','id'=>'dining_room'),
		'bedroom'=>array('loc_id'=>'106','point'=>'(2.414,1.996,1.085)','id'=>'bedroom'),
		'kitchen'=>array('loc_id'=>'107','point'=>'(6.214,2.277,0.749)','id'=>'kitchen'),
        'hallway'=>array('loc_id'=>'108','point'=>'(-0.275,-2.578,2.835)','id'=>'hallway'),

    ),
    'objclass'=>array(
        'bigobjclass'=>array(
            'table'=>array("mcs_table","computer_desk","cupboard","kitchen_table","dining_table","cooking_table","fridge","desk"),
            'shelf'=>array("bookshelf","living_shelf"),
            'appliance'=>array("tv_stand"),
            'seat'=>array("bed","sofa"),
            'room'=>array("living_room","bedroom","workspace","kitchen","hallway","dining_room"),
            'door'=>array("door_a","door_b"),
        ),
        'smallobjclass'=>array(
	        'container'=>array("bowl","plate","storage_box"),
            'drink'=>array("herb_tea","mocha_coffe","asam"),
            'candy'=>array("fries","chewing_gum"),
            'food'=>array("cup_noodle","cake","apple"),
            'snacks'=>array("potato_chips","peach_jelly","sandwich_biscuit"),
            'toiletries'=>array("collar_cleaner"),
        ),
    ),
);
